server:
  port: 9091
spring:
  application:
    name: tensquare-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.100.197.189:3306/tensquare_base?characterEncoding=UTF-8
    username: root
    password: 123456

  jpa:
    database: mysql
    show-sql: true

